name: Continuous Integration

on:
  push:
    branches:
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - develop
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -r requirements-test.txt

    - name: Run unit tests
      run: |
        source .venv/bin/activate
        make model-test

    - name: Collect coverage report
      run: |
        source .venv/bin/activate
        make api-test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
